// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdia5bCbqsPuK7z3jECQT64a3l7N8NVpU',
    appId: '1:361380982242:web:0fe79fe33ab3155fe29dbb',
    messagingSenderId: '361380982242',
    projectId: 'whattobuy-e3713',
    authDomain: 'whattobuy-e3713.firebaseapp.com',
    databaseURL: 'https://whattobuy-e3713.firebaseio.com',
    storageBucket: 'whattobuy-e3713.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7sN6Whl1uXviK6vLRxygi0UQI7gY9NVQ',
    appId: '1:361380982242:android:a3354234f65716cce29dbb',
    messagingSenderId: '361380982242',
    projectId: 'whattobuy-e3713',
    databaseURL: 'https://whattobuy-e3713.firebaseio.com',
    storageBucket: 'whattobuy-e3713.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4AKo6svLnOZijyVkJeDl3vEvekd05TkA',
    appId: '1:361380982242:ios:1d1ffce1bb458780e29dbb',
    messagingSenderId: '361380982242',
    projectId: 'whattobuy-e3713',
    databaseURL: 'https://whattobuy-e3713.firebaseio.com',
    storageBucket: 'whattobuy-e3713.appspot.com',
    androidClientId: '361380982242-78qrre9ugb2dsilst0r1fo1i6htqjtcm.apps.googleusercontent.com',
    iosClientId: '361380982242-9g7st7t3bpq4v17quhpbtq9975h3c4ld.apps.googleusercontent.com',
    iosBundleId: 'ru.ovi.shoppinglist',
  );
}
